require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - 'vendor/bundle/**/*'
    - 'node_modules/**/*'
    - 'bin/**/*'
    - 'db/schema.rb'
  NewCops: enable

Layout/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  Exclude:
    - config/routes.rb

Style/SymbolArray:
  EnforcedStyle: brackets
  MinSize: 2

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
